name: app-build-action-dev

on:
  workflow_dispatch:

jobs:
  # 只打包 Android APK
  build-android:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # 签出代码（自动拉取当前仓库默认分支，解决之前的 ref: dev 报错）
      - uses: actions/checkout@v4

      # 设置 JAVA 环境
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      # 设置 Flutter 环境
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.x"
          cache: true

      # 更新 Flutter 的 packages
      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      # 打包 APK
      - name: Build APK
        run: |
          cd simple_live_app
          flutter build apk --release

      # 上传 APK 产物
      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: simple_live_app/build/app/outputs/flutter-apk/*.apk

      # 完成
      - run: echo "🍏 Android build job status: ${{ job.status }}."
